### ISSUE TITLE
Version 0.18.0: Calling 'bulk_create' raises error 'NoneType' object has no attribute 'executor_class"

### ISSUE THREAD

**Issue by pavdwest** [tortoise/tortoise-orm#1012]
**Describe the bug**
Error is raised when calling bulk_create, e.g. 

```
Tournaments.bulk_create(tournaments)
```
It seems to be coming from ```BulkCreateQuery.__init__``` (queryset.py) when executing line 1713:
```self.executor = self._db.executor_class(model=self.model, db=self._db)```

**To Reproduce**

```
t = {
    "name": "World Cup",
    "description": "Meeting of all teams across the globe."
}
tournaments = [Tournaments(**t)]

Tournaments.bulk_create(tournaments)
```

**Expected behavior**
Update should occur, ```self._db``` should not be None

**Additional context**
Thanks for all the hard work!

**Comment by long2ice** [comment]
But your code is `bulk_update`

**Comment by pavdwest** [comment]
> But your code is `bulk_update`

My apologies - I've updated it. To confirm, the issue is not with ```bulk_update``` but instead with ```bulk_create``` as stated in the description,

**Comment by long2ice** [comment]
Which should be instance of `Tournaments`, not `dict`

**Comment by pavdwest** [comment]
Uurgh, my apologies again, hopefully fixed now. I've tried to simplify my actual example which is as follows FYI:


`async def import_file_without_validation_task_async(filepath: str, model_class_name: str) -> dict:
    try:
        model_klass = globals()[model_class_name]
        crud_klass = globals()[f"{inflection.underscore(model_class_name +'Crud')}"]

        # Lazy load each line into dict and batch up db load
        db_batch_size = 25000
        rows_ready = 0
        total_rows = 0

        with open(filepath, 'r') as f:
            items = list()
            csv_reader = csv.DictReader(f, delimiter='\t')

            async with DbConnection():
                for row in csv_reader:
                    items.append(model_klass(**row))
                    rows_ready += 1

                    # Flush
                    if rows_ready == db_batch_size:
                        res = await crud_klass.bulk_create(items)
                        total_rows += rows_ready
                        logger.info(f"Flushed {rows_ready} rows. (Total {total_rows} and counting...)")
                        rows_ready = 0
                        items.clear()

                # Flush the remaining odd batch
                if rows_ready > 0:
                    total_rows += rows_ready
                    await crud_klass.bulk_create(items)

                return {
                    "msg": "Success",
                    "processed": total_rows,
                }`

The relevant crud method:

`async def bulk_create(items: List[VolumeTests]):
    await VolumeTests.bulk_create(items, batch_size=500, ignore_conflicts=True)
`

**Comment by amirotin** [comment]
Looks like this problem is not solved yet?
I also get same error when calling bulk_create

**Comment by fullonic** [comment]
I got the same issue. @long2ice when will 0.18.1 be released? Thanks
