### ISSUE TITLE
Pydantic model creator not generating correct required fields

### ISSUE THREAD

**Issue by anteatersa** [tortoise/tortoise-orm#1481]
**Describe the bug**
A field in a model with null = True is being marked as required in the generated pydantic schema

**To Reproduce**
Create a new model:

```
class Org(Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=128)
    description = fields.TextField(max_length=2048, null = True)

    def __str__(self):
        return self.name

    class PydanticMeta:
        exclude = ["id"]
```
get the pydantic version:

OrgPydantic = pydantic_model_creator(Org)
OrgPydantic.model_json_schema()

output will have both name and description set as required:

{'additionalProperties': False, 'properties': {'name': {'maxLength': 128, 'title': 'Name', 'type': 'string'}, 'description': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'nullable': True, 'title': 'Description'}}, **'required': ['name', 'description']**, 'title': 'Org', 'type': 'object'}

**Expected behavior**
I would expect that only name would be in the required list

**Comment by anteatersa** [comment]
I believe the issue is [here](https://github.com/tortoise/tortoise-orm/blob/develop/tortoise/contrib/pydantic/creator.py#L398)

`ptype = Optional[ptype]
`
In the pydantic docs they state the following:

    f1: str  # required, cannot be None
    f2: Optional[str]  # required, can be None - same as str | None
    **f3: Optional[str] = None  # not required, can be None**
    f4: str = 'Foobar'  # not required, but cannot be None

So in order for the field to be not required it would have to be defined as:

`Optional[ptype] = None
`
but this is ibviously a syntax error

**Comment by plusiv** [comment]
There's a Pull Request (#1465) open to solve this.

**Comment by plusiv** [comment]
Hi @long2ice ! I think this issue should be closed as it was resolved in #1465

**Comment by pawelkoston** [comment]
It was not resolved, because of https://github.com/tortoise/tortoise-orm/commit/3fc4ea08e4033653391ed52fd9cf7ccc68d54fa3#diff-11de455fd99e247aa87d1d404e00da4d54d83e5b2e06b5e37585bdd8f2b8c169R419
Having TextField or Intfield not required in schema is not possible.

**Comment by abondar** [comment]
Fixed in 1.0.0
